package com.theapp

/**
 * Complete O*NET Occupations Database
 * 637 careers with smart RIASEC filtering
 */
object OccupationsDatabase {
    
    // All occupations alphabetically
    val allOccupations = listOf(
        "Acupuncturists",
        "Actors",
        "Adapted Physical Education Specialists",
        "Adhesive Bonding Machine Operators and Tenders",
        "Administrative Law Judges, Adjudicators, and Hearing Officers",
        "Advanced Practice Psychiatric Nurses",
        "Agricultural Sciences Teachers, Postsecondary",
        "Allergists and Immunologists",
        "Anesthesiologist Assistants",
        "Anesthesiologists",
        "Animal Scientists",
        "Anthropologists and Archeologists",
        "Anthropology and Archeology Teachers, Postsecondary",
        "Arbitrators, Mediators, and Conciliators",
        "Architects, Except Landscape and Naval",
        "Architectural and Engineering Managers",
        "Architecture Teachers, Postsecondary",
        "Archivists",
        "Area, Ethnic, and Cultural Studies Teachers, Postsecondary",
        "Art Therapists",
        "Art, Drama, and Music Teachers, Postsecondary",
        "Astronomers",
        "Athletic Trainers",
        "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary",
        "Audiologists",
        "Biochemists and Biophysicists",
        "Bioinformatics Scientists",
        "Biological Science Teachers, Postsecondary",
        "Biologists",
        "Biostatisticians",
        "Business Teachers, Postsecondary",
        "Cardiologists",
        "Chemistry Teachers, Postsecondary",
        "Chief Executives",
        "Chief Sustainability Officers",
        "Chiropractors",
        "Clergy",
        "Climate Change Policy Analysts",
        "Clinical and Counseling Psychologists",
        "Clinical Neuropsychologists",
        "Clinical Nurse Specialists",
        "Communications Teachers, Postsecondary",
        "Computer and Information Research Scientists",
        "Computer Science Teachers, Postsecondary",
        "Criminal Justice and Law Enforcement Teachers, Postsecondary",
        "Curators",
        "Cytotechnologists",
        "Dentists, General",
        "Dermatologists",
        "Dietitians and Nutritionists",
        "Economics Teachers, Postsecondary",
        "Economists",
        "Education Administrators, Kindergarten through Secondary",
        "Education Administrators, Postsecondary",
        "Education Teachers, Postsecondary",
        "Educational, Guidance, and Career Counselors and Advisors",
        "Emergency Medicine Physicians",
        "Engineering Teachers, Postsecondary",
        "English Language and Literature Teachers, Postsecondary",
        "Environmental Economists",
        "Environmental Restoration Planners",
        "Environmental Science Teachers, Postsecondary",
        "Epidemiologists",
        "Family and Consumer Sciences Teachers, Postsecondary",
        "Family Medicine Physicians",
        "Farm and Home Management Educators",
        "Financial Quantitative Analysts",
        "Foreign Language and Literature Teachers, Postsecondary",
        "Forestry and Conservation Science Teachers, Postsecondary",
        "General Internal Medicine Physicians",
        "Genetic Counselors",
        "Geneticists",
        "Geography Teachers, Postsecondary",
        "Geoscientists, Except Hydrologists and Geographers",
        "Health Informatics Specialists",
        "Health Specialties Teachers, Postsecondary",
        "Healthcare Social Workers",
        "Historians",
        "History Teachers, Postsecondary",
        "Hospitalists",
        "Human Factors Engineers and Ergonomists",
        "Hydrologists",
        "Industrial Ecologists",
        "Industrial-Organizational Psychologists",
        "Instructional Coordinators",
        "Investment Fund Managers",
        "Judges, Magistrate Judges, and Magistrates",
        "Judicial Law Clerks",
        "Law Teachers, Postsecondary",
        "Lawyers",
        "Librarians and Media Collections Specialists",
        "Library Science Teachers, Postsecondary",
        "Low Vision Therapists, Orientation and Mobility Specialists, and Vision Rehabilitation Therapists",
        "Marriage and Family Therapists",
        "Mathematical Science Teachers, Postsecondary",
        "Mathematicians",
        "Medical Scientists, Except Epidemiologists",
        "Mental Health and Substance Abuse Social Workers",
        "Mental Health Counselors",
        "Microsystems Engineers",
        "Midwives",
        "Molecular and Cellular Biologists",
        "Nanosystems Engineers",
        "Natural Sciences Managers",
        "Naturopathic Physicians",
        "Neurologists",
        "Neuropsychologists",
        "Nurse Anesthetists",
        "Nurse Midwives",
        "Nurse Practitioners",
        "Nursing Instructors and Teachers, Postsecondary",
        "Obstetricians and Gynecologists",
        "Occupational Therapists",
        "Operations Research Analysts",
        "Ophthalmologists, Except Pediatric",
        "Optometrists",
        "Oral and Maxillofacial Surgeons",
        "Orthodontists",
        "Orthopedic Surgeons, Except Pediatric",
        "Orthoptists",
        "Orthotists and Prosthetists",
        "Pediatric Surgeons",
        "Pediatricians, General",
        "Pharmacists",
        "Philosophy and Religion Teachers, Postsecondary",
        "Physical Medicine and Rehabilitation Physicians",
        "Physical Therapists",
        "Physician Assistants",
        "Physicians, Pathologists",
        "Physicists",
        "Physics Teachers, Postsecondary",
        "Podiatrists",
        "Political Science Teachers, Postsecondary",
        "Political Scientists",
        "Preventive Medicine Physicians",
        "Prosthodontists",
        "Psychiatrists",
        "Psychology Teachers, Postsecondary",
        "Radiologists",
        "Recreation and Fitness Studies Teachers, Postsecondary",
        "School Psychologists",
        "Set and Exhibit Designers",
        "Social Work Teachers, Postsecondary",
        "Sociologists",
        "Sociology Teachers, Postsecondary",
        "Soil and Plant Scientists",
        "Special Education Teachers, Preschool",
        "Speech-Language Pathologists",
        "Sports Medicine Physicians",
        "Statisticians",
        "Substance Abuse and Behavioral Disorder Counselors",
        "Survey Researchers",
        "Teaching Assistants, Postsecondary",
        "Urban and Regional Planners",
        "Urologists",
        "Veterinarians",
        "Administrative Services Managers",
        "Aerospace Engineering and Operations Technologists and Technicians",
        "Agricultural Equipment Operators",
        "Agricultural Inspectors",
        "Agricultural Technicians",
        "Agricultural Workers, All Other",
        "Air Crew Members",
        "Air Crew Officers",
        "Air Traffic Controllers",
        "Aircraft Cargo Handling Supervisors",
        "Aircraft Launch and Recovery Officers",
        "Aircraft Launch and Recovery Specialists",
        "Aircraft Mechanics and Service Technicians",
        "Aircraft Service Attendants",
        "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers",
        "Airfield Operations Specialists",
        "Ambulance Drivers and Attendants, Except Emergency Medical Technicians",
        "Amusement and Recreation Attendants",
        "Animal Breeders",
        "Animal Caretakers",
        "Animal Control Workers",
        "Animal Trainers",
        "Architectural and Civil Drafters",
        "Armored Assault Vehicle Crew Members",
        "Armored Assault Vehicle Officers",
        "Artillery and Missile Crew Members",
        "Artillery and Missile Officers",
        "Artists and Related Workers, All Other",
        "Assemblers and Fabricators, All Other",
        "Athletes and Sports Competitors",
        "Audio and Video Technicians",
        "Audiovisual Equipment Installers and Repairers",
        "Automotive Body and Related Repairers",
        "Automotive Engineering Technicians",
        "Automotive Glass Installers and Repairers",
        "Automotive Service Technicians and Mechanics",
        "Automotive and Watercraft Service Attendants",
        "Aviation Inspectors",
        "Avionics Technicians",
        "Baggage Porters and Bellhops",
        "Bailiffs",
        "Bakers",
        "Barbers",
        "Baristas",
        "Bartenders",
        "Bicycle Repairers",
        "Bill and Account Collectors",
        "Billing and Posting Clerks",
        "Biofuels Processing Technicians",
        "Biological Scientists, All Other",
        "Biomass Plant Technicians",
        "Boilermakers",
        "Bookkeeping, Accounting, and Auditing Clerks",
        "Brickmasons and Blockmasons",
        "Bridge and Lock Tenders",
        "Broadcast Technicians",
        "Brokerage Clerks",
        "Building Cleaning Workers, All Other",
        "Bus Drivers, School",
        "Bus Drivers, Transit and Intercity",
        "Bus and Truck Mechanics and Diesel Engine Specialists",
        "Business Operations Specialists, All Other",
        "Butchers and Meat Cutters",
        "Cabinetmakers and Bench Carpenters",
        "Calibration Technologists and Technicians",
        "Camera Operators, Television, Video, and Film",
        "Camera and Photographic Equipment Repairers",
        "Captains, Mates, and Pilots of Water Vessels",
        "Cardiovascular Technologists and Technicians",
        "Career/Technical Education Teachers, Postsecondary",
        "Cargo and Freight Agents",
        "Carpenters",
        "Carpet Installers",
        "Cashiers",
        "Cement Masons and Concrete Finishers",
        "Chefs and Head Cooks",
        "Chemical Equipment Operators and Tenders",
        "Chemical Plant and System Operators",
        "Chemical Technicians",
        "Childcare Workers",
        "Choreographers",
        "Civil Engineering Technologists and Technicians",
        "Cleaners of Vehicles and Equipment",
        "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders",
        "Coating, Painting, and Spraying Machine Setters, Operators, and Tenders",
        "Coil Winders, Tapers, and Finishers",
        "Coin, Vending, and Amusement Machine Servicers and Repairers",
        "Command and Control Center Officers",
        "Command and Control Center Specialists",
        "Commercial Divers",
        "Commercial Pilots",
        "Communications Equipment Operators, All Other",
        "Community and Social Service Specialists, All Other",
        "Computer Numerically Controlled Tool Operators",
        "Computer Numerically Controlled Tool Programmers",
        "Computer Occupations, All Other",
        "Computer Systems Analysts",
        "Computer Systems Engineers/Architects",
        "Computer User Support Specialists",
        "Computer, Automated Teller, and Office Machine Repairers",
        "Concierges",
        "Construction Laborers",
        "Construction and Building Inspectors",
        "Construction and Related Workers, All Other",
        "Continuous Mining Machine Operators",
        "Control and Valve Installers and Repairers, Except Mechanical Door",
        "Conveyor Operators and Tenders",
        "Cooks, All Other",
        "Cooks, Fast Food",
        "Cooks, Institution and Cafeteria",
        "Cooks, Private Household",
        "Cooks, Restaurant",
        "Cooks, Short Order",
        "Cooling and Freezing Equipment Operators and Tenders",
        "Coroners",
        "Correctional Officers and Jailers",
        "Correspondence Clerks",
        "Costume Attendants",
        "Counselors, All Other",
        "Counter and Rental Clerks",
        "Couriers and Messengers",
        "Court Reporters and Simultaneous Captioners",
        "Court, Municipal, and License Clerks",
        "Craft Artists",
        "Crane and Tower Operators",
        "Credit Authorizers, Checkers, and Clerks",
        "Crematory Operators",
        "Crossing Guards and Flaggers",
        "Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders",
        "Customer Service Representatives",
        "Customs Brokers",
        "Customs and Border Protection Officers",
        "Cutters and Trimmers, Hand",
        "Cutting and Slicing Machine Setters, Operators, and Tenders",
        "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Dancers",
        "Data Entry Keyers",
        "Demonstrators and Product Promoters",
        "Dental Assistants",
        "Dental Hygienists",
        "Dental Laboratory Technicians",
        "Dentists, All Other Specialists",
        "Derrick Operators, Oil and Gas",
        "Designers, All Other",
        "Desktop Publishers",
        "Detectives and Criminal Investigators",
        "Diagnostic Medical Sonographers",
        "Dietetic Technicians",
        "Dining Room and Cafeteria Attendants and Bartender Helpers",
        "Disc Jockeys, Except Radio",
        "Dishwashers",
        "Dispatchers, Except Police, Fire, and Ambulance",
        "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers",
        "Drafters, All Other",
        "Dredge Operators",
        "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "Driver/Sales Workers",
        "Drywall and Ceiling Tile Installers",
        "Earth Drillers, Except Oil and Gas",
        "Education Administrators, All Other",
        "Educational Instruction and Library Workers, All Other",
        "Electric Motor, Power Tool, and Related Repairers",
        "Electrical Power-Line Installers and Repairers",
        "Electrical and Electronic Engineering Technologists and Technicians",
        "Electrical and Electronic Equipment Assemblers",
        "Electrical and Electronics Drafters",
        "Electrical and Electronics Installers and Repairers, Transportation Equipment",
        "Electrical and Electronics Repairers, Commercial and Industrial Equipment",
        "Electrical and Electronics Repairers, Powerhouse, Substation, and Relay",
        "Electricians",
        "Electro-Mechanical and Mechatronics Technologists and Technicians",
        "Electromechanical Equipment Assemblers",
        "Electronic Equipment Installers and Repairers, Motor Vehicles",
        "Elevator and Escalator Installers and Repairers",
        "Eligibility Interviewers, Government Programs",
        "Embalmers",
        "Emergency Medical Technicians",
        "Endoscopy Technicians",
        "Energy Auditors",
        "Engine and Other Machine Assemblers",
        "Engineering Technologists and Technicians, Except Drafters, All Other",
        "Engineers, All Other",
        "Entertainers and Performers, Sports and Related Workers, All Other",
        "Entertainment Attendants and Related Workers, All Other",
        "Etchers and Engravers",
        "Excavating and Loading Machine and Dragline Operators, Surface Mining",
        "Executive Secretaries and Executive Administrative Assistants",
        "Exercise Trainers and Group Fitness Instructors",
        "Explosives Workers, Ordnance Handling Experts, and Blasters",
        "Extraction Workers, All Other",
        "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers",
        "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders",
        "Fabric and Apparel Patternmakers",
        "Facilities Managers",
        "Fallers",
        "Farm Equipment Mechanics and Service Technicians",
        "Farm Labor Contractors",
        "Farmworkers and Laborers, Crop, Nursery, and Greenhouse",
        "Farmworkers, Farm, Ranch, and Aquacultural Animals",
        "Fashion Designers",
        "Fast Food and Counter Workers",
        "Fence Erectors",
        "Fiberglass Laminators and Fabricators",
        "File Clerks",
        "Financial Clerks, All Other",
        "Financial Specialists, All Other",
        "Fine Artists, Including Painters, Sculptors, and Illustrators",
        "Fire Inspectors and Investigators",
        "Firefighters",
        "First-Line Supervisors of Air Crew Members",
        "First-Line Supervisors of All Other Tactical Operations Specialists",
        "First-Line Supervisors of Construction Trades and Extraction Workers",
        "First-Line Supervisors of Correctional Officers",
        "First-Line Supervisors of Entertainment and Recreation Workers, Except Gambling Services",
        "First-Line Supervisors of Farming, Fishing, and Forestry Workers",
        "First-Line Supervisors of Firefighting and Prevention Workers",
        "First-Line Supervisors of Food Preparation and Serving Workers",
        "First-Line Supervisors of Gambling Services Workers",
        "First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand",
        "First-Line Supervisors of Housekeeping and Janitorial Workers",
        "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers",
        "First-Line Supervisors of Material-Moving Machine and Vehicle Operators",
        "First-Line Supervisors of Mechanics, Installers, and Repairers",
        "First-Line Supervisors of Office and Administrative Support Workers",
        "First-Line Supervisors of Passenger Attendants",
        "First-Line Supervisors of Personal Service Workers",
        "First-Line Supervisors of Police and Detectives",
        "First-Line Supervisors of Production and Operating Workers",
        "First-Line Supervisors of Protective Service Workers, All Other",
        "First-Line Supervisors of Retail Sales Workers",
        "First-Line Supervisors of Security Workers",
        "First-Line Supervisors of Transportation Workers, All Other",
        "First-Line Supervisors of Weapons Specialists/Crew Members",
        "Fishing and Hunting Workers",
        "Flight Attendants",
        "Floor Layers, Except Carpet, Wood, and Hard Tiles",
        "Floor Sanders and Finishers",
        "Floral Designers",
        "Food Batchmakers",
        "Food Cooking Machine Operators and Tenders",
        "Food Preparation Workers",
        "Food Preparation and Serving Related Workers, All Other",
        "Food Processing Workers, All Other",
        "Food Science Technicians",
        "Food Servers, Nonrestaurant",
        "Food Service Managers",
        "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders",
        "Forensic Science Technicians",
        "Forest Fire Inspectors and Prevention Specialists",
        "Forest and Conservation Technicians",
        "Forest and Conservation Workers",
        "Forging Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Foundry Mold and Coremakers",
        "Freight Forwarders",
        "Funeral Attendants",
        "Funeral Home Managers",
        "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders",
        "Furniture Finishers",
        "Gambling Cage Workers",
        "Gambling Change Persons and Booth Cashiers",
        "Gambling Dealers",
        "Gambling Managers",
        "Gambling Service Workers, All Other",
        "Gambling Surveillance Officers and Gambling Investigators",
        "Gambling and Sports Book Writers and Runners",
        "Gas Compressor and Gas Pumping Station Operators",
        "Gas Plant Operators",
        "Gem and Diamond Workers",
        "Geographic Information Systems Technologists and Technicians",
        "Geothermal Production Managers",
        "Geothermal Technicians",
        "Glass Blowers, Molders, Benders, and Finishers",
        "Glaziers",
        "Government Property Inspectors and Investigators",
        "Graders and Sorters, Agricultural Products",
        "Grinding and Polishing Workers, Hand",
        "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "Grounds Maintenance Workers, All Other",
        "Hairdressers, Hairstylists, and Cosmetologists",
        "Hazardous Materials Removal Workers",
        "Health Information Technologists and Medical Registrars",
        "Health Technologists and Technicians, All Other",
        "Healthcare Diagnosing or Treating Practitioners, All Other",
        "Healthcare Practitioners and Technical Workers, All Other",
        "Healthcare Support Workers, All Other",
        "Hearing Aid Specialists",
        "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic",
        "Heating, Air Conditioning, and Refrigeration Mechanics and Installers",
        "Heavy and Tractor-Trailer Truck Drivers",
        "Helpers, Construction Trades, All Other",
        "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters",
        "Helpers--Carpenters",
        "Helpers--Electricians",
        "Helpers--Extraction Workers",
        "Helpers--Installation, Maintenance, and Repair Workers",
        "Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons",
        "Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters",
        "Helpers--Production Workers",
        "Helpers--Roofers",
        "Highway Maintenance Workers",
        "Histology Technicians",
        "Hoist and Winch Operators",
        "Home Appliance Repairers",
        "Home Health Aides",
        "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop",
        "Hotel, Motel, and Resort Desk Clerks",
        "Human Resources Assistants, Except Payroll and Timekeeping",
        "Hydroelectric Plant Technicians",
        "Hydroelectric Production Managers",
        "Hydrologic Technicians",
        "Industrial Engineering Technologists and Technicians",
        "Industrial Machinery Mechanics",
        "Industrial Truck and Tractor Operators",
        "Infantry",
        "Infantry Officers",
        "Information and Record Clerks, All Other",
        "Inspectors, Testers, Sorters, Samplers, and Weighers",
        "Installation, Maintenance, and Repair Workers, All Other",
        "Insulation Workers, Floor, Ceiling, and Wall",
        "Insulation Workers, Mechanical",
        "Insurance Appraisers, Auto Damage",
        "Insurance Claims and Policy Processing Clerks",
        "Interviewers, Except Eligibility and Loan",
        "Janitors and Cleaners, Except Maids and Housekeeping Cleaners",
        "Jewelers and Precious Stone and Metal Workers",
        "Laborers and Freight, Stock, and Material Movers, Hand",
        "Landscaping and Groundskeeping Workers",
        "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "Laundry and Dry-Cleaning Workers",
        "Layout Workers, Metal and Plastic",
        "Legal Secretaries and Administrative Assistants",
        "Legal Support Workers, All Other",
        "Library Assistants, Clerical",
        "Library Technicians",
        "Licensed Practical and Licensed Vocational Nurses",
        "Life Scientists, All Other",
        "Life, Physical, and Social Science Technicians, All Other",
        "Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers",
        "Light Truck Drivers",
        "Lighting Technicians",
        "Loading and Moving Machine Operators, Underground Mining",
        "Loan Interviewers and Clerks",
        "Locker Room, Coatroom, and Dressing Room Attendants",
        "Locksmiths and Safe Repairers",
        "Locomotive Engineers",
        "Log Graders and Scalers",
        "Logging Equipment Operators",
        "Logging Workers, All Other",
        "Machine Feeders and Offbearers",
        "Machinists",
        "Magnetic Resonance Imaging Technologists",
        "Maids and Housekeeping Cleaners",
        "Mail Clerks and Mail Machine Operators, Except Postal Service",
        "Maintenance Workers, Machinery",
        "Maintenance and Repair Workers, General",
        "Makeup Artists, Theatrical and Performance",
        "Managers, All Other",
        "Manicurists and Pedicurists",
        "Manufactured Building and Mobile Home Installers",
        "Massage Therapists",
        "Material Moving Workers, All Other",
        "Mathematical Science Occupations, All Other",
        "Meat, Poultry, and Fish Cutters and Trimmers",
        "Mechanical Door Repairers",
        "Mechanical Drafters",
        "Mechanical Engineering Technologists and Technicians",
        "Media and Communication Equipment Workers, All Other",
        "Media and Communication Workers, All Other",
        "Medical Appliance Technicians",
        "Medical Assistants",
        "Medical Equipment Preparers",
        "Medical Equipment Repairers",
        "Medical Records Specialists",
        "Medical Secretaries and Administrative Assistants",
        "Medical Transcriptionists",
        "Medical and Clinical Laboratory Technicians",
        "Merchandise Displayers and Window Trimmers",
        "Metal Workers and Plastic Workers, All Other",
        "Metal-Refining Furnace Operators and Tenders",
        "Meter Readers, Utilities",
        "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other",
        "Military Officer Special and Tactical Operations Leaders, All Other",
        "Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Millwrights",
        "Mixing and Blending Machine Setters, Operators, and Tenders",
        "Mobile Heavy Equipment Mechanics, Except Engines",
        "Model Makers, Metal and Plastic",
        "Model Makers, Wood",
        "Models",
        "Molders, Shapers, and Casters, Except Metal and Plastic",
        "Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Morticians, Undertakers, and Funeral Arrangers",
        "Motion Picture Projectionists",
        "Motor Vehicle Operators, All Other",
        "Motorboat Mechanics and Service Technicians",
        "Motorboat Operators",
        "Motorcycle Mechanics",
        "Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic",
        "Musical Instrument Repairers and Tuners",
        "Nannies",
        "Neurodiagnostic Technologists",
        "New Accounts Clerks",
        "Non-Destructive Testing Specialists",
        "Nuclear Medicine Technologists",
        "Nuclear Monitoring Technicians",
        "Nuclear Power Reactor Operators",
        "Nuclear Technicians",
        "Nursing Assistants",
        "Occupational Health and Safety Technicians",
        "Occupational Therapy Aides",
        "Occupational Therapy Assistants",
        "Office Clerks, General",
        "Office Machine Operators, Except Computer",
        "Office and Administrative Support Workers, All Other",
        "Operating Engineers and Other Construction Equipment Operators",
        "Ophthalmic Laboratory Technicians",
        "Ophthalmic Medical Technicians",
        "Ophthalmic Medical Technologists",
        "Opticians, Dispensing",
        "Order Clerks",
        "Orderlies",
        "Outdoor Power Equipment and Other Small Engine Mechanics",
        "Packaging and Filling Machine Operators and Tenders",
        "Packers and Packagers, Hand",
        "Painters, Construction and Maintenance",
        "Painting, Coating, and Decorating Workers",
        "Paper Goods Machine Setters, Operators, and Tenders",
        "Paperhangers",
        "Paralegals and Legal Assistants",
        "Paramedics",
        "Parking Attendants",
        "Parking Enforcement Workers",
        "Parts Salespersons",
        "Passenger Attendants",
        "Patient Representatives",
        "Patternmakers, Metal and Plastic",
        "Patternmakers, Wood",
        "Paving, Surfacing, and Tamping Equipment Operators",
        "Payroll and Timekeeping Clerks",
        "Personal Care Aides",
        "Personal Care and Service Workers, All Other",
        "Personal Service Managers, All Other",
        "Pest Control Workers",
        "Pesticide Handlers, Sprayers, and Applicators, Vegetation",
        "Petroleum Pump System Operators, Refinery Operators, and Gaugers",
        "Pharmacy Aides",
        "Pharmacy Technicians",
        "Phlebotomists",
        "Photographers",
        "Photographic Process Workers and Processing Machine Operators",
        "Photonics Technicians",
        "Physical Scientists, All Other",
        "Physical Therapist Aides",
        "Physical Therapist Assistants",
        "Physicians, All Other",
        "Pile Driver Operators",
        "Pipelayers",
        "Plant and System Operators, All Other",
        "Plasterers and Stucco Masons",
        "Plating Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Plumbers, Pipefitters, and Steamfitters",
        "Police Identification and Records Officers",
        "Police and Sheriff's Patrol Officers",
        "Postal Service Clerks",
        "Postal Service Mail Carriers",
        "Postal Service Mail Sorters, Processors, and Processing Machine Operators",
        "Postmasters and Mail Superintendents",
        "Postsecondary Teachers, All Other",
        "Potters, Manufacturing",
        "Pourers and Casters, Metal",
        "Power Distributors and Dispatchers",
        "Power Plant Operators",
        "Precision Agriculture Technicians",
        "Precision Instrument and Equipment Repairers, All Other",
        "Prepress Technicians and Workers",
        "Preschool Teachers, Except Special Education",
        "Pressers, Textile, Garment, and Related Materials",
        "Print Binding and Finishing Workers",
        "Printing Press Operators",
        "Private Detectives and Investigators",
        "Procurement Clerks",
        "Production Workers, All Other",
        "Production, Planning, and Expediting Clerks",
        "Protective Service Workers, All Other",
        "Psychiatric Aides",
        "Psychiatric Technicians",
        "Psychologists, All Other",
        "Public Safety Telecommunicators",
        "Pump Operators, Except Wellhead Pumpers",
        "Quality Control Analysts",
        "Radiation Therapists",
        "Radio, Cellular, and Tower Equipment Installers and Repairers",
        "Radiologic Technologists and Technicians",
        "Rail Car Repairers",
        "Rail Transportation Workers, All Other",
        "Rail Yard Engineers, Dinkey Operators, and Hostlers",
        "Rail-Track Laying and Maintenance Equipment Operators",
        "Railroad Brake, Signal, and Switch Operators and Locomotive Firers",
        "Railroad Conductors and Yardmasters",
        "Real Estate Sales Agents",
        "Receptionists and Information Clerks",
        "Recreational Vehicle Service Technicians",
        "Recycling Coordinators",
        "Recycling and Reclamation Workers",
        "Refractory Materials Repairers, Except Brickmasons",
        "Refuse and Recyclable Material Collectors",
        "Reinforcing Iron and Rebar Workers",
        "Religious Workers, All Other",
        "Reservation and Transportation Ticket Agents and Travel Clerks",
        "Residential Advisors",
        "Respiratory Therapists",
        "Retail Loss Prevention Specialists",
        "Retail Salespersons",
        "Riggers",
        "Robotics Technicians",
        "Rock Splitters, Quarry",
        "Rolling Machine Setters, Operators, and Tenders, Metal and Plastic",
        "Roof Bolters, Mining",
        "Roofers",
        "Rotary Drill Operators, Oil and Gas",
        "Roustabouts, Oil and Gas",
        "Sailors and Marine Oilers",
        "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel",
        "Sales and Related Workers, All Other",
        "Sawing Machine Setters, Operators, and Tenders, Wood",
        "School Bus Monitors",
        "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
        "Security Guards",
        "Security and Fire Alarm Systems Installers",
        "Segmental Pavers",
        "Self-Enrichment Teachers",
        "Semiconductor Processing Technicians",
        "Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders",
        "Septic Tank Servicers and Sewer Pipe Cleaners",
        "Service Unit Operators, Oil and Gas",
        "Sewers, Hand",
        "Sewing Machine Operators",
        "Shampooers",
        "Sheet Metal Workers",
        "Ship Engineers",
        "Shipping, Receiving, and Inventory Clerks",
        "Shoe Machine Operators and Tenders",
        "Shoe and Leather Workers and Repairers",
        "Shuttle Drivers and Chauffeurs",
        "Signal and Track Switch Repairers",
        "Skincare Specialists",
        "Slaughterers and Meat Packers",
        "Social Sciences Teachers, Postsecondary, All Other",
        "Social Scientists and Related Workers, All Other",
        "Social Workers, All Other",
        "Solar Energy Installation Managers",
        "Solar Photovoltaic Installers",
        "Solar Sales Representatives and Assessors",
        "Solar Thermal Installers and Technicians",
        "Sound Engineering Technicians",
        "Spa Managers",
        "Special Education Teachers, All Other",
        "Special Forces",
        "Special Forces Officers",
        "Speech-Language Pathology Assistants",
        "Stationary Engineers and Boiler Operators",
        "Stockers and Order Fillers",
        "Stone Cutters and Carvers, Manufacturing",
        "Stonemasons",
        "Structural Iron and Steel Workers",
        "Structural Metal Fabricators and Fitters",
        "Subway and Streetcar Operators",
        "Surgeons, All Other",
        "Surgical Assistants",
        "Surgical Technologists",
        "Surveying and Mapping Technicians",
        "Switchboard Operators, Including Answering Service",
        "Tailors, Dressmakers, and Custom Sewers",
        "Tank Car, Truck, and Ship Loaders",
        "Tapers",
        "Tax Examiners and Collectors, and Revenue Agents",
        "Tax Preparers",
        "Taxi Drivers",
        "Teachers and Instructors, All Other",
        "Teaching Assistants, All Other",
        "Teaching Assistants, Preschool, Elementary, Middle, and Secondary School, Except Special Education",
        "Teaching Assistants, Special Education",
        "Team Assemblers",
        "Telecommunications Engineering Specialists",
        "Telecommunications Equipment Installers and Repairers, Except Line Installers",
        "Telecommunications Line Installers and Repairers",
        "Telemarketers",
        "Telephone Operators",
        "Tellers",
        "Terrazzo Workers and Finishers",
        "Textile Bleaching and Dyeing Machine Operators and Tenders",
        "Textile Cutting Machine Setters, Operators, and Tenders",
        "Textile Knitting and Weaving Machine Setters, Operators, and Tenders",
        "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders",
        "Textile, Apparel, and Furnishings Workers, All Other",
        "Therapists, All Other",
        "Tile and Stone Setters",
        "Timing Device Assemblers and Adjusters",
        "Tire Builders",
        "Tire Repairers and Changers",
        "Title Examiners, Abstractors, and Searchers",
        "Tool Grinders, Filers, and Sharpeners",
        "Tool and Die Makers",
        "Tour Guides and Escorts",
        "Traffic Technicians",
        "Transit and Railroad Police",
        "Transportation Security Screeners",
        "Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation",
        "Transportation Workers, All Other",
        "Travel Agents",
        "Travel Guides",
        "Tree Trimmers and Pruners",
        "Tutors",
        "Umpires, Referees, and Other Sports Officials",
        "Underground Mining Machine Operators, All Other",
        "Upholsterers",
        "Ushers, Lobby Attendants, and Ticket Takers",
        "Veterinary Assistants and Laboratory Animal Caretakers",
        "Veterinary Technologists and Technicians",
        "Waiters and Waitresses",
        "Watch and Clock Repairers",
        "Water and Wastewater Treatment Plant and System Operators",
        "Weatherization Installers and Technicians",
        "Web Developers",
        "Weighers, Measurers, Checkers, and Samplers, Recordkeeping",
        "Welders, Cutters, Solderers, and Brazers",
        "Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders",
        "Wellhead Pumpers",
        "Wholesale and Retail Buyers, Except Farm Products",
        "Wind Energy Operations Managers",
        "Wind Turbine Service Technicians",
        "Woodworkers, All Other",
        "Woodworking Machine Setters, Operators, and Tenders, Except Sawing",
        "Word Processors and Typists",
        "﻿Acute Care Nurses",
    )
    
    // Keywords for RIASEC personality types
    private val typeKeywords = mapOf(
        "R" to listOf("engineer", "mechanic", "technician", "pilot", "construction", "electrician", "plumber", "welder", "machinist", "installer", "repairer", "operator", "driver", "equipment", "maintenance", "industrial", "manufacturing", "automotive", "aircraft", "diesel", "hvac", "boiler", "crane", "heavy", "truck", "mining", "oil", "gas", "power", "plant", "solar", "wind", "energy", "surveyor", "drafter", "inspector", "firefighter", "police", "military", "crew", "officer"),
        "I" to listOf("scientist", "researcher", "analyst", "data", "software", "computer", "information", "database", "network", "systems", "programmer", "developer", "web", "security", "physician", "doctor", "medical", "health", "clinical", "laboratory", "technologist", "biologist", "chemist", "physicist", "mathematician", "statistician", "economist", "psychologist", "sociologist", "anthropologist", "geographer", "historian", "political", "urban", "planner", "environmental", "conservation", "research", "epidemiologist", "geneticist", "microbiologist", "biochemist"),
        "A" to listOf("designer", "artist", "writer", "author", "editor", "musician", "singer", "composer", "dancer", "choreographer", "actor", "director", "producer", "photographer", "camera", "film", "video", "broadcast", "announcer", "reporter", "journalist", "news", "media", "graphic", "interior", "fashion", "commercial", "industrial", "floral", "craft", "fine", "multimedia", "animator", "illustrator", "exhibit", "set", "makeup", "costume", "creative", "poet", "lyricist", "technical writer", "interpreter", "translator"),
        "S" to listOf("teacher", "instructor", "educator", "professor", "counselor", "therapist", "social worker", "nurse", "nursing", "healthcare", "medical assistant", "dental", "physical therapist", "occupational therapist", "speech", "respiratory", "radiation", "dietitian", "nutritionist", "pharmacist", "physician assistant", "midwife", "chiropractor", "optometrist", "podiatrist", "veterinarian", "clergy", "religious", "recreation", "fitness", "coach", "trainer", "childcare", "preschool", "kindergarten", "elementary", "middle school", "secondary", "special education", "guidance", "rehabilitation", "substance abuse", "mental health", "marriage", "family"),
        "E" to listOf("manager", "director", "executive", "administrator", "chief", "supervisor", "sales", "marketing", "business", "operations", "general manager", "financial manager", "human resources", "purchasing", "training", "development", "compensation", "benefits", "compliance", "regulatory", "fundraising", "public relations", "advertising", "promotions", "real estate", "broker", "agent", "property", "lodging", "food service", "entertainment", "recreation", "meeting", "event", "planner", "lawyer", "judge", "legislator", "arbitrator", "mediator", "entrepreneur", "merchant", "buyer", "loan officer", "insurance", "securities", "investment"),
        "C" to listOf("accountant", "auditor", "bookkeeper", "payroll", "billing", "clerk", "administrative", "secretary", "receptionist", "office", "data entry", "word processor", "typist", "file", "mail", "postal", "shipping", "receiving", "inventory", "stock", "order", "procurement", "production planning", "expediting", "dispatcher", "scheduler", "customer service", "information clerk", "interviewer", "teller", "cashier", "counter", "reservation", "ticket", "court reporter", "legal assistant", "paralegal", "medical records", "health information", "library assistant", "budget analyst", "financial analyst", "credit analyst", "tax", "claims", "insurance", "brokerage", "compliance officer", "inspector", "examiner", "appraiser")
    )
    
    /**
     * Get occupations filtered by personality type
     */
    fun getOccupationsByType(primaryType: String, secondaryType: String? = null): List<String> {
        val primaryKeywords = typeKeywords[primaryType] ?: emptyList()
        val secondaryKeywords = if (secondaryType != null) typeKeywords[secondaryType] ?: emptyList() else emptyList()
        val allKeywords = primaryKeywords + secondaryKeywords
        
        val filtered = allOccupations.filter { occupation ->
            val lowerOccupation = occupation.lowercase()
            allKeywords.any { keyword -> lowerOccupation.contains(keyword) }
        }
        
        return if (filtered.isNotEmpty()) filtered else allOccupations
    }
    
    /**
     * Convert occupation name to slug
     */
    fun occupationToSlug(name: String): String {
        return name.lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .trim('-')
    }
}
