package com.theapp

/**
 * Maps occupation display names to database slugs
 * Auto-generated from FINAL_COMPLETE_ALL_ROADMAPS.js
 * Total: 386 occupations
 * Generated: 2025-11-09 22:52:07
 */
object OccupationMapper {
    
    private val occupationMap = mapOf(
        "acupuncturists" to "acupuncturists",
        "adapted physical education specialists" to "adapted-physical-education-specialists",
        "administrative law judges adjudicators and hearing officers" to "administrative-law-judges-adjudicators-and-hearing-officers",
        "advanced practice psychiatric nurses" to "advanced-practice-psychiatric-nurses",
        "agricultural sciences teachers postsecondary" to "agricultural-sciences-teachers-postsecondary",
        "allergists and immunologists" to "allergists-and-immunologists",
        "anesthesiologist assistants" to "anesthesiologist-assistants",
        "anesthesiologists" to "anesthesiologists",
        "animal scientists" to "animal-scientists",
        "anthropologists and archeologists" to "anthropologists-and-archeologists",
        "anthropology and archeology teachers postsecondary" to "anthropology-and-archeology-teachers-postsecondary",
        "arbitrators mediators and conciliators" to "arbitrators-mediators-and-conciliators",
        "architects except landscape and naval" to "architects-except-landscape-and-naval",
        "architectural and engineering managers" to "architectural-and-engineering-managers",
        "architecture teachers postsecondary" to "architecture-teachers-postsecondary",
        "archivists" to "archivists",
        "area ethnic and cultural studies teachers postsecondary" to "area-ethnic-and-cultural-studies-teachers-postsecondary",
        "art therapists" to "art-therapists",
        "art drama and music teachers postsecondary" to "art-drama-and-music-teachers-postsecondary",
        "astronomers" to "astronomers",
        "athletic trainers" to "athletic-trainers",
        "atmospheric earth marine and space sciences teachers postsecondary" to "atmospheric-earth-marine-and-space-sciences-teachers-postsecondary",
        "audiologists" to "audiologists",
        "biochemists and biophysicists" to "biochemists-and-biophysicists",
        "bioinformatics scientists" to "bioinformatics-scientists",
        "biological science teachers postsecondary" to "biological-science-teachers-postsecondary",
        "biologists" to "biologists",
        "biostatisticians" to "biostatisticians",
        "business teachers postsecondary" to "business-teachers-postsecondary",
        "cardiologists" to "cardiologists",
        "chemistry teachers postsecondary" to "chemistry-teachers-postsecondary",
        "chief executives" to "chief-executives",
        "chief sustainability officers" to "chief-sustainability-officers",
        "chiropractors" to "chiropractors",
        "clergy" to "clergy",
        "climate change policy analysts" to "climate-change-policy-analysts",
        "clinical and counseling psychologists" to "clinical-and-counseling-psychologists",
        "clinical neuropsychologists" to "clinical-neuropsychologists",
        "clinical nurse specialists" to "clinical-nurse-specialists",
        "communications teachers postsecondary" to "communications-teachers-postsecondary",
        "computer and information research scientists" to "computer-and-information-research-scientists",
        "computer science teachers postsecondary" to "computer-science-teachers-postsecondary",
        "criminal justice and law enforcement teachers postsecondary" to "criminal-justice-and-law-enforcement-teachers-postsecondary",
        "curators" to "curators",
        "cytotechnologists" to "cytotechnologists",
        "dentists general" to "dentists-general",
        "dermatologists" to "dermatologists",
        "dietitians and nutritionists" to "dietitians-and-nutritionists",
        "economics teachers postsecondary" to "economics-teachers-postsecondary",
        "economists" to "economists",
        "education administrators kindergarten through secondary" to "education-administrators-kindergarten-through-secondary",
        "education administrators postsecondary" to "education-administrators-postsecondary",
        "education teachers postsecondary" to "education-teachers-postsecondary",
        "educational guidance and career counselors and advisors" to "educational-guidance-and-career-counselors-and-advisors",
        "emergency medicine physicians" to "emergency-medicine-physicians",
        "engineering teachers postsecondary" to "engineering-teachers-postsecondary",
        "english language and literature teachers postsecondary" to "english-language-and-literature-teachers-postsecondary",
        "environmental economists" to "environmental-economists",
        "environmental restoration planners" to "environmental-restoration-planners",
        "environmental science teachers postsecondary" to "environmental-science-teachers-postsecondary",
        "epidemiologists" to "epidemiologists",
        "family and consumer sciences teachers postsecondary" to "family-and-consumer-sciences-teachers-postsecondary",
        "family medicine physicians" to "family-medicine-physicians",
        "farm and home management educators" to "farm-and-home-management-educators",
        "financial quantitative analysts" to "financial-quantitative-analysts",
        "foreign language and literature teachers postsecondary" to "foreign-language-and-literature-teachers-postsecondary",
        "forestry and conservation science teachers postsecondary" to "forestry-and-conservation-science-teachers-postsecondary",
        "general internal medicine physicians" to "general-internal-medicine-physicians",
        "genetic counselors" to "genetic-counselors",
        "geneticists" to "geneticists",
        "geography teachers postsecondary" to "geography-teachers-postsecondary",
        "geoscientists except hydrologists and geographers" to "geoscientists-except-hydrologists-and-geographers",
        "health informatics specialists" to "health-informatics-specialists",
        "health specialties teachers postsecondary" to "health-specialties-teachers-postsecondary",
        "healthcare social workers" to "healthcare-social-workers",
        "historians" to "historians",
        "history teachers postsecondary" to "history-teachers-postsecondary",
        "hospitalists" to "hospitalists",
        "human factors engineers and ergonomists" to "human-factors-engineers-and-ergonomists",
        "hydrologists" to "hydrologists",
        "industrial ecologists" to "industrial-ecologists",
        "industrial organizational psychologists" to "industrial-organizational-psychologists",
        "instructional coordinators" to "instructional-coordinators",
        "investment fund managers" to "investment-fund-managers",
        "judges magistrate judges and magistrates" to "judges-magistrate-judges-and-magistrates",
        "judicial law clerks" to "judicial-law-clerks",
        "law teachers postsecondary" to "law-teachers-postsecondary",
        "lawyers" to "lawyers",
        "librarians and media collections specialists" to "librarians-and-media-collections-specialists",
        "library science teachers postsecondary" to "library-science-teachers-postsecondary",
        "low vision therapists orientation and mobility specialists and vision rehabilitation therapists" to "low-vision-therapists-orientation-and-mobility-specialists-and-vision-rehabilitation-therapists",
        "marriage and family therapists" to "marriage-and-family-therapists",
        "mathematical science teachers postsecondary" to "mathematical-science-teachers-postsecondary",
        "mathematicians" to "mathematicians",
        "medical scientists except epidemiologists" to "medical-scientists-except-epidemiologists",
        "mental health and substance abuse social workers" to "mental-health-and-substance-abuse-social-workers",
        "mental health counselors" to "mental-health-counselors",
        "microsystems engineers" to "microsystems-engineers",
        "midwives" to "midwives",
        "molecular and cellular biologists" to "molecular-and-cellular-biologists",
        "nanosystems engineers" to "nanosystems-engineers",
        "natural sciences managers" to "natural-sciences-managers",
        "naturopathic physicians" to "naturopathic-physicians",
        "neurologists" to "neurologists",
        "neuropsychologists" to "neuropsychologists",
        "nurse anesthetists" to "nurse-anesthetists",
        "nurse midwives" to "nurse-midwives",
        "nurse practitioners" to "nurse-practitioners",
        "nursing instructors and teachers postsecondary" to "nursing-instructors-and-teachers-postsecondary",
        "obstetricians and gynecologists" to "obstetricians-and-gynecologists",
        "occupational therapists" to "occupational-therapists",
        "operations research analysts" to "operations-research-analysts",
        "ophthalmologists except pediatric" to "ophthalmologists-except-pediatric",
        "optometrists" to "optometrists",
        "oral and maxillofacial surgeons" to "oral-and-maxillofacial-surgeons",
        "orthodontists" to "orthodontists",
        "orthopedic surgeons except pediatric" to "orthopedic-surgeons-except-pediatric",
        "orthoptists" to "orthoptists",
        "orthotists and prosthetists" to "orthotists-and-prosthetists",
        "pediatric surgeons" to "pediatric-surgeons",
        "pediatricians general" to "pediatricians-general",
        "pharmacists" to "pharmacists",
        "philosophy and religion teachers postsecondary" to "philosophy-and-religion-teachers-postsecondary",
        "physical medicine and rehabilitation physicians" to "physical-medicine-and-rehabilitation-physicians",
        "physical therapists" to "physical-therapists",
        "physician assistants" to "physician-assistants",
        "physicians pathologists" to "physicians-pathologists",
        "physicists" to "physicists",
        "physics teachers postsecondary" to "physics-teachers-postsecondary",
        "podiatrists" to "podiatrists",
        "political science teachers postsecondary" to "political-science-teachers-postsecondary",
        "political scientists" to "political-scientists",
        "preventive medicine physicians" to "preventive-medicine-physicians",
        "prosthodontists" to "prosthodontists",
        "psychiatrists" to "psychiatrists",
        "psychology teachers postsecondary" to "psychology-teachers-postsecondary",
        "radiologists" to "radiologists",
        "recreation and fitness studies teachers postsecondary" to "recreation-and-fitness-studies-teachers-postsecondary",
        "school psychologists" to "school-psychologists",
        "set and exhibit designers" to "set-and-exhibit-designers",
        "social work teachers postsecondary" to "social-work-teachers-postsecondary",
        "sociologists" to "sociologists",
        "sociology teachers postsecondary" to "sociology-teachers-postsecondary",
        "soil and plant scientists" to "soil-and-plant-scientists",
        "special education teachers preschool" to "special-education-teachers-preschool",
        "speech language pathologists" to "speech-language-pathologists",
        "sports medicine physicians" to "sports-medicine-physicians",
        "statisticians" to "statisticians",
        "substance abuse and behavioral disorder counselors" to "substance-abuse-and-behavioral-disorder-counselors",
        "survey researchers" to "survey-researchers",
        "teaching assistants postsecondary" to "teaching-assistants-postsecondary",
        "urban and regional planners" to "urban-and-regional-planners",
        "urologists" to "urologists",
        "veterinarians" to "veterinarians",
        "accountants and auditors" to "accountants-and-auditors",
        "actuaries" to "actuaries",
        "adult basic education adult secondary education and english as a second language instructors" to "adult-basic-education-adult-secondary-education-and-english-as-a-second-language-instructors",
        "advertising and promotions managers" to "advertising-and-promotions-managers",
        "advertising sales agents" to "advertising-sales-agents",
        "aerospace engineers" to "aerospace-engineers",
        "agents and business managers of artists performers and athletes" to "agents-and-business-managers-of-artists-performers-and-athletes",
        "agricultural engineers" to "agricultural-engineers",
        "airline pilots copilots and flight engineers" to "airline-pilots-copilots-and-flight-engineers",
        "appraisers and assessors of real estate" to "appraisers-and-assessors-of-real-estate",
        "appraisers of personal and business property" to "appraisers-of-personal-and-business-property",
        "art directors" to "art-directors",
        "atmospheric and space scientists" to "atmospheric-and-space-scientists",
        "automotive engineers" to "automotive-engineers",
        "bioengineers and biomedical engineers" to "bioengineers-and-biomedical-engineers",
        "biofuels production managers" to "biofuels-production-managers",
        "biofuelsbiodiesel technology and product development managers" to "biofuelsbiodiesel-technology-and-product-development-managers",
        "bioinformatics technicians" to "bioinformatics-technicians",
        "biological technicians" to "biological-technicians",
        "biomass power plant managers" to "biomass-power-plant-managers",
        "blockchain engineers" to "blockchain-engineers",
        "broadcast announcers and radio disc jockeys" to "broadcast-announcers-and-radio-disc-jockeys",
        "brownfield redevelopment specialists and site managers" to "brownfield-redevelopment-specialists-and-site-managers",
        "budget analysts" to "budget-analysts",
        "business continuity planners" to "business-continuity-planners",
        "business intelligence analysts" to "business-intelligence-analysts",
        "buyers and purchasing agents farm products" to "buyers-and-purchasing-agents-farm-products",
        "careertechnical education teachers middle school" to "careertechnical-education-teachers-middle-school",
        "careertechnical education teachers secondary school" to "careertechnical-education-teachers-secondary-school",
        "cartographers and photogrammetrists" to "cartographers-and-photogrammetrists",
        "chemical engineers" to "chemical-engineers",
        "chemists" to "chemists",
        "child family and school social workers" to "child-family-and-school-social-workers",
        "civil engineers" to "civil-engineers",
        "claims adjusters examiners and investigators" to "claims-adjusters-examiners-and-investigators",
        "clinical data managers" to "clinical-data-managers",
        "clinical research coordinators" to "clinical-research-coordinators",
        "coaches and scouts" to "coaches-and-scouts",
        "commercial and industrial designers" to "commercial-and-industrial-designers",
        "community health workers" to "community-health-workers",
        "compensation and benefits managers" to "compensation-and-benefits-managers",
        "compensation benefits and job analysis specialists" to "compensation-benefits-and-job-analysis-specialists",
        "compliance managers" to "compliance-managers",
        "compliance officers" to "compliance-officers",
        "computer and information systems managers" to "computer-and-information-systems-managers",
        "computer hardware engineers" to "computer-hardware-engineers",
        "computer network architects" to "computer-network-architects",
        "computer network support specialists" to "computer-network-support-specialists",
        "computer programmers" to "computer-programmers",
        "conservation scientists" to "conservation-scientists",
        "construction managers" to "construction-managers",
        "cost estimators" to "cost-estimators",
        "credit analysts" to "credit-analysts",
        "credit counselors" to "credit-counselors",
        "critical care nurses" to "critical-care-nurses",
        "cytogenetic technologists" to "cytogenetic-technologists",
        "data scientists" to "data-scientists",
        "data warehousing specialists" to "data-warehousing-specialists",
        "database administrators" to "database-administrators",
        "database architects" to "database-architects",
        "digital forensics analysts" to "digital-forensics-analysts",
        "directors religious activities and education" to "directors-religious-activities-and-education",
        "document management specialists" to "document-management-specialists",
        "editors" to "editors",
        "education and childcare administrators preschool and daycare" to "education-and-childcare-administrators-preschool-and-daycare",
        "electrical engineers" to "electrical-engineers",
        "electronics engineers except computer" to "electronics-engineers-except-computer",
        "elementary school teachers except special education" to "elementary-school-teachers-except-special-education",
        "emergency management directors" to "emergency-management-directors",
        "energy engineers except wind and solar" to "energy-engineers-except-wind-and-solar",
        "entertainment and recreation managers except gambling" to "entertainment-and-recreation-managers-except-gambling",
        "environmental compliance inspectors" to "environmental-compliance-inspectors",
        "environmental engineering technologists and technicians" to "environmental-engineering-technologists-and-technicians",
        "environmental engineers" to "environmental-engineers",
        "environmental science and protection technicians including health" to "environmental-science-and-protection-technicians-including-health",
        "environmental scientists and specialists including health" to "environmental-scientists-and-specialists-including-health",
        "equal opportunity representatives and officers" to "equal-opportunity-representatives-and-officers",
        "exercise physiologists" to "exercise-physiologists",
        "farmers ranchers and other agricultural managers" to "farmers-ranchers-and-other-agricultural-managers",
        "film and video editors" to "film-and-video-editors",
        "financial and investment analysts" to "financial-and-investment-analysts",
        "financial examiners" to "financial-examiners",
        "financial managers" to "financial-managers",
        "financial risk specialists" to "financial-risk-specialists",
        "fire prevention and protection engineers" to "fire-prevention-and-protection-engineers",
        "first line supervisors of non retail sales workers" to "first-line-supervisors-of-non-retail-sales-workers",
        "fish and game wardens" to "fish-and-game-wardens",
        "fitness and wellness coordinators" to "fitness-and-wellness-coordinators",
        "food scientists and technologists" to "food-scientists-and-technologists",
        "foresters" to "foresters",
        "fraud examiners investigators and analysts" to "fraud-examiners-investigators-and-analysts",
        "fuel cell engineers" to "fuel-cell-engineers",
        "fundraisers" to "fundraisers",
        "fundraising managers" to "fundraising-managers",
        "general and operations managers" to "general-and-operations-managers",
        "geodetic surveyors" to "geodetic-surveyors",
        "geographers" to "geographers",
        "geological technicians except hydrologic technicians" to "geological-technicians-except-hydrologic-technicians",
        "graphic designers" to "graphic-designers",
        "health and safety engineers except mining safety engineers and inspectors" to "health-and-safety-engineers-except-mining-safety-engineers-and-inspectors",
        "health education specialists" to "health-education-specialists",
        "acute care nurses" to "acute-care-nurses",
        "administrative services managers" to "administrative-services-managers",
        "aerospace engineering and operations technologists and technicians" to "aerospace-engineering-and-operations-technologists-and-technicians",
        "agricultural technicians" to "agricultural-technicians",
        "air traffic controllers" to "air-traffic-controllers",
        "aircraft mechanics and service technicians" to "aircraft-mechanics-and-service-technicians",
        "airfield operations specialists" to "airfield-operations-specialists",
        "architectural and civil drafters" to "architectural-and-civil-drafters",
        "audio and video technicians" to "audio-and-video-technicians",
        "audiovisual equipment installers and repairers" to "audiovisual-equipment-installers-and-repairers",
        "automotive engineering technicians" to "automotive-engineering-technicians",
        "automotive service technicians and mechanics" to "automotive-service-technicians-and-mechanics",
        "aviation inspectors" to "aviation-inspectors",
        "avionics technicians" to "avionics-technicians",
        "bailiffs" to "bailiffs",
        "barbers" to "barbers",
        "billing and posting clerks" to "billing-and-posting-clerks",
        "boilermakers" to "boilermakers",
        "bookkeeping accounting and auditing clerks" to "bookkeeping-accounting-and-auditing-clerks",
        "broadcast technicians" to "broadcast-technicians",
        "brokerage clerks" to "brokerage-clerks",
        "bus and truck mechanics and diesel engine specialists" to "bus-and-truck-mechanics-and-diesel-engine-specialists",
        "calibration technologists and technicians" to "calibration-technologists-and-technicians",
        "camera and photographic equipment repairers" to "camera-and-photographic-equipment-repairers",
        "camera operators television video and film" to "camera-operators-television-video-and-film",
        "captains mates and pilots of water vessels" to "captains-mates-and-pilots-of-water-vessels",
        "cardiovascular technologists and technicians" to "cardiovascular-technologists-and-technicians",
        "careertechnical education teachers postsecondary" to "careertechnical-education-teachers-postsecondary",
        "chefs and head cooks" to "chefs-and-head-cooks",
        "chemical technicians" to "chemical-technicians",
        "choreographers" to "choreographers",
        "civil engineering technologists and technicians" to "civil-engineering-technologists-and-technicians",
        "commercial divers" to "commercial-divers",
        "commercial pilots" to "commercial-pilots",
        "computer numerically controlled tool programmers" to "computer-numerically-controlled-tool-programmers",
        "computer systems analysts" to "computer-systems-analysts",
        "computer systems engineersarchitects" to "computer-systems-engineersarchitects",
        "computer user support specialists" to "computer-user-support-specialists",
        "computer automated teller and office machine repairers" to "computer-automated-teller-and-office-machine-repairers",
        "concierges" to "concierges",
        "construction and building inspectors" to "construction-and-building-inspectors",
        "control and valve installers and repairers except mechanical door" to "control-and-valve-installers-and-repairers-except-mechanical-door",
        "cooks private household" to "cooks-private-household",
        "coroners" to "coroners",
        "court reporters and simultaneous captioners" to "court-reporters-and-simultaneous-captioners",
        "craft artists" to "craft-artists",
        "crane and tower operators" to "crane-and-tower-operators",
        "customs and border protection officers" to "customs-and-border-protection-officers",
        "customs brokers" to "customs-brokers",
        "dancers" to "dancers",
        "actors" to "actors",
        "adhesive bonding machine operators and tenders" to "adhesive-bonding-machine-operators-and-tenders",
        "agricultural inspectors" to "agricultural-inspectors",
        "aircraft cargo handling supervisors" to "aircraft-cargo-handling-supervisors",
        "aircraft service attendants" to "aircraft-service-attendants",
        "aircraft structure surfaces rigging and systems assemblers" to "aircraft-structure-surfaces-rigging-and-systems-assemblers",
        "ambulance drivers and attendants except emergency medical technicians" to "ambulance-drivers-and-attendants-except-emergency-medical-technicians",
        "animal breeders" to "animal-breeders",
        "animal caretakers" to "animal-caretakers",
        "animal control workers" to "animal-control-workers",
        "animal trainers" to "animal-trainers",
        "athletes and sports competitors" to "athletes-and-sports-competitors",
        "automotive and watercraft service attendants" to "automotive-and-watercraft-service-attendants",
        "automotive body and related repairers" to "automotive-body-and-related-repairers",
        "automotive glass installers and repairers" to "automotive-glass-installers-and-repairers",
        "baggage porters and bellhops" to "baggage-porters-and-bellhops",
        "bakers" to "bakers",
        "bartenders" to "bartenders",
        "bicycle repairers" to "bicycle-repairers",
        "bill and account collectors" to "bill-and-account-collectors",
        "biofuels processing technicians" to "biofuels-processing-technicians",
        "biomass plant technicians" to "biomass-plant-technicians",
        "brickmasons and blockmasons" to "brickmasons-and-blockmasons",
        "bridge and lock tenders" to "bridge-and-lock-tenders",
        "bus drivers school" to "bus-drivers-school",
        "bus drivers transit and intercity" to "bus-drivers-transit-and-intercity",
        "butchers and meat cutters" to "butchers-and-meat-cutters",
        "cabinetmakers and bench carpenters" to "cabinetmakers-and-bench-carpenters",
        "cargo and freight agents" to "cargo-and-freight-agents",
        "carpenters" to "carpenters",
        "carpet installers" to "carpet-installers",
        "cashiers" to "cashiers",
        "chemical equipment operators and tenders" to "chemical-equipment-operators-and-tenders",
        "chemical plant and system operators" to "chemical-plant-and-system-operators",
        "childcare workers" to "childcare-workers",
        "cleaners of vehicles and equipment" to "cleaners-of-vehicles-and-equipment",
        "cleaning washing and metal pickling equipment operators and tenders" to "cleaning-washing-and-metal-pickling-equipment-operators-and-tenders",
        "coating painting and spraying machine setters operators and tenders" to "coating-painting-and-spraying-machine-setters-operators-and-tenders",
        "coil winders tapers and finishers" to "coil-winders-tapers-and-finishers",
        "coin vending and amusement machine servicers and repairers" to "coin-vending-and-amusement-machine-servicers-and-repairers",
        "computer numerically controlled tool operators" to "computer-numerically-controlled-tool-operators",
        "construction laborers" to "construction-laborers",
        "continuous mining machine operators" to "continuous-mining-machine-operators",
        "cooks institution and cafeteria" to "cooks-institution-and-cafeteria",
        "cooks restaurant" to "cooks-restaurant",
        "cooks short order" to "cooks-short-order",
        "cooling and freezing equipment operators and tenders" to "cooling-and-freezing-equipment-operators-and-tenders",
        "correctional officers and jailers" to "correctional-officers-and-jailers",
        "correspondence clerks" to "correspondence-clerks",
        "costume attendants" to "costume-attendants",
        "agricultural equipment operators" to "agricultural-equipment-operators",
        "amusement and recreation attendants" to "amusement-and-recreation-attendants",
        "baristas" to "baristas",
        "cement masons and concrete finishers" to "cement-masons-and-concrete-finishers",
        "conveyor operators and tenders" to "conveyor-operators-and-tenders",
        "cooks fast food" to "cooks-fast-food",
        "cutters and trimmers hand" to "cutters-and-trimmers-hand",
        "derrick operators oil and gas" to "derrick-operators-oil-and-gas",
        "dining room and cafeteria attendants and bartender helpers" to "dining-room-and-cafeteria-attendants-and-bartender-helpers",
        "dishwashers" to "dishwashers",
        "door to door sales workers news and street vendors and related workers" to "door-to-door-sales-workers-news-and-street-vendors-and-related-workers",
        "fallers" to "fallers",
        "farmworkers and laborers crop nursery and greenhouse" to "farmworkers-and-laborers-crop-nursery-and-greenhouse",
        "fast food and counter workers" to "fast-food-and-counter-workers",
        "fishing and hunting workers" to "fishing-and-hunting-workers",
        "floor sanders and finishers" to "floor-sanders-and-finishers",
        "graders and sorters agricultural products" to "graders-and-sorters-agricultural-products",
        "helpers painters paperhangers plasterers and stucco masons" to "helpers-painters-paperhangers-plasterers-and-stucco-masons",
        "landscaping and groundskeeping workers" to "landscaping-and-groundskeeping-workers",
        "laundry and dry cleaning workers" to "laundry-and-dry-cleaning-workers",
        "logging equipment operators" to "logging-equipment-operators",
        "maids and housekeeping cleaners" to "maids-and-housekeeping-cleaners",
        "meat poultry and fish cutters and trimmers" to "meat-poultry-and-fish-cutters-and-trimmers",
        "painting coating and decorating workers" to "painting-coating-and-decorating-workers",
        "plasterers and stucco masons" to "plasterers-and-stucco-masons",
        "pressers textile garment and related materials" to "pressers-textile-garment-and-related-materials",
        "rock splitters quarry" to "rock-splitters-quarry",
        "roustabouts oil and gas" to "roustabouts-oil-and-gas",
        "septic tank servicers and sewer pipe cleaners" to "septic-tank-servicers-and-sewer-pipe-cleaners",
        "sewers hand" to "sewers-hand",
        "sewing machine operators" to "sewing-machine-operators"
    )
    
    /**
     * Get database slug for occupation name
     * @param occupationName Display name of occupation
     * @return Database slug or null if not found
     */
    fun getSlug(occupationName: String): String? {
        val normalized = occupationName.lowercase().trim()
        return occupationMap[normalized]
    }
    
    /**
     * Check if occupation has a mapping
     */
    fun hasMapping(occupationName: String): Boolean {
        return getSlug(occupationName) != null
    }
    
    /**
     * Get all mapped occupation names
     */
    fun getAllMappedOccupations(): List<String> {
        return occupationMap.keys.toList()
    }
    
    /**
     * Get count of mapped occupations
     */
    fun getTotalCount(): Int {
        return occupationMap.size
    }
    
    /**
     * Search occupations by keyword
     */
    fun searchOccupations(keyword: String): List<String> {
        val lowerKeyword = keyword.lowercase()
        return occupationMap.keys.filter { it.contains(lowerKeyword) }
    }
}
